### ISSUE TITLE
Decoder Binary

### ISSUE THREAD

**Issue by Natrinicle** [sz3/libcimbar#62]
I came across https://github.com/dzhang314/YouTubeDrive and recalled downloading and playing around with your Camera File Copy application. It's a wonderful idea but I also really like the idea and I see a couple of potential use cases.

* Being able to upload a file to a video hosting service (while not abusing the privilege) and then using a downloader to recover that file
* Sending that video via some sort of filesharing service from computer to computer (not super useful but interesting from the point of view of steganography)
* The ability to transfer a file to/from an airgapped machine using a webcam

Do you by chance have a decoder binary able to be built for a computer already in the repo and I've missed it or would it be possible to request such a binary be added so that recovery isn't limited to an Android device?

**Comment by sz3** [comment]
Thanks for the issue -- even if there are some tools to this end (`cimbar` and `cimbar_recv`), there's still some work to be done IMO.

Breaking it down a bit based on my (limited) research into it:
* The `cimbar` executable operates on one or a series of images, not a video feed. This probably won't change -- it's supposed to be a simple tool.
    * however, it should really have a way to operate on a continuous feed of images -- that is, a user should be able to continuously generate new images and send them to a running `cimbar` process (for example through stdin).
    * the obvious thing to do would be to have it read line-delimited filenames from stdin as inputs. It does not currently do this, but it wouldn't be too much work and this is a good reminder that I should probably just make this change.
* The `cimbar_recv` executable operates on a video feed -- specifically, it operates on an opencv *device*, which can be a camera or (maybe) a video file?
    * This is a recent addition and not fully baked, however.
* in regards to encoding videos of cimbar output in general: I think this *should* work, but there are some sneaky and diabolical things video compression does to the feed in my limited experiments with it. But something like a 15fps cimbar feed encoded at 30fps (each frame twice), or a 20fps feed encoded at 60fps (each frame thrice) might do the trick.
