### ISSUE TITLE
Install via termux

### ISSUE THREAD

**Issue by Ygarr** [sz3/libcimbar#64]
Is it possible to install cimbar_send using android terminal?

**Comment by sz3** [comment]
It is not. However, if you're trying to do encode while offline (e.g. you can't access cimbar.org), you should be able to download [cimbar_js](https://github.com/sz3/libcimbar/releases/download/v0.5.12/cimbar.html) to your phone and open it in mobile Chrome.

**Comment by Ygarr** [comment]
Thanks.Great. I've got the encoded animated square with symbols and shaking edges. So it is hard to focus camera on it with receiver smartphone. Is it correct behaviour?

**Comment by sz3** [comment]
I'd try increasing the screen brightness on the sender to see if that helps. Otherwise you might have to "trick" the autofocus on the receiver into finding the right focus (I usually use my finger for that).

Some phones have autofocus that works well for cimbar, others seem to have problems.
