### ISSUE TITLE
camera model

### ISSUE THREAD

**Issue by yuanshengyong** [sz3/libcimbar#65]
Hi,
Could you tell me the camera model you used to test the decoding under Ubuntu？
Thanks!

**Comment by yuanshengyong** [comment]
How to compile a project on Windows？

**Comment by sz3** [comment]
The camera I'm testing with is a Razer Kizer Pro. Any 1080p camera could work, though it is a bit difficult to get it set up right. `cimbar_recv` has rough edges...

The requirements are:
* a *1080p* webcam -- on linux, test with `cheese` or `obs-studio`, or ...
* enough usb bandwidth to maintain 1080p. This can vary by usb port (ex: USB3 vs USB2).
    * some USB-C hubs have given me issues -- making it necessary to drop the capture resolution down to 720p or 480p. Since cimbar needs ~1000 pixels of vertical resolution, 1080p is essential.
    * this can be verified with `cheese` or other camera apps
* figure out what video device your camera is plugged in on. This can be done with `v4l2-ctl --list-devices` (apt install v4l-utils)
    * linux camera devices will be of the form `/dev/video0`, `/dev/video1`
* run cimbar_recv: ex: `./cimbar_recv -i /dev/video2 -o /tmp`
   * point the camera at a cimbar feed!
   * your enemies are autofocus, glare, shaky hands, etc.

As for Windows builds -- unfortunately, it's not likely right now. One day, perhaps, but there will need to be changes, and I don't use Windows these days (so testing will be difficult on my end).

**Comment by yuanshengyong** [comment]
Thank you for your answer。

**Comment by yuanshengyong** [comment]
What is the transmission rate of the Razer Kiyo Pro camera on Linux

**Comment by sz3** [comment]
> What is the transmission rate of the Razer Kiyo Pro camera on Linux

The camera itself is 60fps at 1080p (which is why I bought it), but as for cimbar transfer speeds on linux -- I don't know! My android tests have been focused on performance, but the linux tests are still in the "how well does this work?" phase.

I will say that it's more difficult to hold the image steady on a webcam (compared to a phone) -- and based on my tests, autofocus is a menace (the native app probably should have manual focus options).

**Comment by yuanshengyong** [comment]
Thank you for your answer！！！
