### ISSUE TITLE
QR code codec library 

### ISSUE THREAD

**Issue by yuanshengyong** [sz3/libcimbar#66]
Hello, the QR code codec library you use? I'm learning about it. Can you provide your implementation plan?

**Comment by sz3** [comment]
I'm not sure I understand your question. But maybe I can offer some random thoughts that might help?

* cimbar is significantly different from QR codes -- there is very little in common (perhaps code that checks for the finder pattern, if that)
* for understanding how cimbar works, the python prototype is probably the easiest way: https://github.com/sz3/cimbar
   * I've been meaning to write up various details on the implementation in a series of blog posts/articles, but I haven't gotten around to it yet. :thinking: 
   * I'd say the key concepts are: image hashing, forward error correction (reedsolomon), and fountain codes (wirehair).

Let me know if any of that was helpful. :slightly_smiling_face:

**Comment by yuanshengyong** [comment]
I want to know whether you implement putting data into pictures, using a third-party library or by yourself

**Comment by sz3** [comment]
libcimbar does most of the work itself. But it does use `opencv` to manipulate the image pixels.

![4 bit cimbar encoding](https://github.com/sz3/cimbar-samples/blob/v0.5/docs/encoding.png)

**Comment by yuanshengyong** [comment]
Thank you for your answer。
