### ISSUE TITLE
Wondering how this would perform if you use monochrome mode.

### ISSUE THREAD

**Issue by mofosyne** [sz3/libcimbar#70]
I see you only appear to support 4-bit and 8-bit colour mode. Just wondering how it would work if its a 1-bit monochrome and if it would do well or worse against QR code.

**Comment by sz3** [comment]
> if it would do well or worse against QR code.

So, the answer here is going to be along the lines of: it depends on the use case.

The background is that the max capacity for a QR code is about 3kb, and a monochromatic cimbar code (in the current implementation) is about 5kb of data. But that isn't a fair comparison -- QR codes are using a lot less space. cimbar is optimized for a computer screen refreshing the image 15+ times a second, and a cell phone decoder being able to keep up with that data stream -- so it's making tradeoffs that would help it do better in other scenarios.

The question I'd ask is: what's the scenario we're envisioning where we don't have access to colors? That scenario -- perhaps "a bar code printed on paper being scanned by someone" likely has significantly different constraints, and QR codes were designed with those constraints in mind. So all things being equal, QR codes *should* (and will, I think?) be superior vs the current cimbar implementation.
