### ISSUE TITLE
What files are needed to compile the wasm for HTML, and what other parameters are needed？

### ISSUE THREAD

**Issue by DebugNoob** [sz3/libcimbar#74]
HI, your project is amazing to me.
 I want to try modifying some parameters to compile wasm and encountered some issues. 
What files are needed to compile the wasm for HTML, and what other parameters are needed?

**Comment by sz3** [comment]
For the wasm build (and the asm.js build), I use a docker container and run this script inside it. The docker command is the (commented out) 2nd line of the script:
https://github.com/sz3/libcimbar/blob/master/package-wasm.sh

You can also see how it's used by the github actions workflow [here](https://github.com/sz3/libcimbar/blob/master/.github/workflows/release.yml#L17-L30). The only real interesting thing is that you need to download opencv and extract it to the `opencv4/` subdirectory ahead of time.

**Comment by DebugNoob** [comment]
Thank you very much ^_^.
But I have encountered a new problem that I searched the internet but couldn't find the relevant answer. 
Have you encountered it again? 
When I execute to
`Python 3/ Platforms/js/build_ Js.py build_ Wasm -- build_ Wasm -- embedded_ When dir=/emsdk/upstream/subscripten`
an error was reported
```
clang++: error: unsupported option' - arch='for target' wasm32 unknown subscripten
Em++: error: '/emsdk/upstream/bin/clang++- target wasm32 unknown emscripten
```
😢

**Comment by sz3** [comment]
Ok, I'm seeing the same thing when using `emscripten-latest`. Thanks for noticing this... I think I'll just pin the emscripten image to something slightly older (that also works).

**Comment by sz3** [comment]
`emscripten/emsdk:3.1.39` works.

**Comment by sz3** [comment]
https://github.com/sz3/libcimbar/pull/75

**Comment by DebugNoob** [comment]
Thank you very much! 
Wishing you great success in your future work!
