### ISSUE TITLE
no issue working well & this is fun

### ISSUE THREAD

**Issue by chienhao10** [sz3/libcimbar#98]
just want to say this is kinda fun, although 12mb apk file took me about 3~4min to download. perhaps smaller file will be faster to send, this is very usefull for me when im having trouble connect device to pc.
maybe i can record down as gif and loop let others download the file, im thinking how this can be used

**Comment by sz3** [comment]
Thanks!

At some point there should be a faster version, but not all of my experiments have worked out... faster would be great, but there are laws of physics to deal with.

I think a 2x speed increase is possible, but going past that will probably make it trickier to use -- more sensitive to lighting among other things. I'm aiming for a version that can hit around 150 KB/s for now.
